<a href="https://colab.research.google.com/github/ikhadeer07/Numpy-Programs/blob/main/numpy_7_programms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# create a NumPy array
arr = np.array([2, 5, 1, 9, 3, 7])

# find the maximum element using numpy.amax()
max_element = np.amax(arr)
print("Maximum element:", max_element)

# find the minimum element using numpy.amin()
min_element = np.amin(arr)
print("Minimum element:", min_element)


Maximum element: 9
Minimum element: 1


In [2]:
import numpy as np

# create a NumPy array
arr = np.array([2, 5, 1, 9, 3, 7])

# sort the elements using numpy.sort()
sorted_arr = np.sort(arr)
print("Sorted array:", sorted_arr)


Sorted array: [1 2 3 5 7 9]


In [3]:
import numpy as np

# create a list of NumPy arrays
arr_list = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]

# find the mean of each array using numpy.mean()
mean_list = [np.mean(arr) for arr in arr_list]
print("Mean of each array:", mean_list)


Mean of each array: [2.0, 5.0, 8.0]


In [4]:
import numpy as np

# create a 2D NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# add a row to the array using numpy.vstack()
new_row = np.array([7, 8, 9])
arr_with_row = np.vstack((arr, new_row))
print("Array with new row:\n", arr_with_row)

# add a column to the array using numpy.hstack()
new_col = np.array([[10], [11]])
arr_with_col = np.hstack((arr, new_col))
print("Array with new column:\n", arr_with_col)


Array with new row:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array with new column:
 [[ 1  2  3 10]
 [ 4  5  6 11]]


In [5]:
import numpy as np

# create a 1D NumPy array
arr1d = np.array([1, 2, 3, 4, 5])

# reverse the array using numpy.flip()
arr1d_reverse = np.flip(arr1d)
print("Reversed 1D array:", arr1d_reverse)

# create a 2D NumPy array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# reverse the array along the rows using numpy.flip()
arr2d_reverse_rows = np.flip(arr2d, axis=0)
print("Reversed 2D array along rows:\n", arr2d_reverse_rows)

# reverse the array along the columns using numpy.flip()
arr2d_reverse_cols = np.flip(arr2d, axis=1)
print("Reversed 2D array along columns:\n", arr2d_reverse_cols)


Reversed 1D array: [5 4 3 2 1]
Reversed 2D array along rows:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed 2D array along columns:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [6]:
import numpy as np

# create two matrices
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[7, 8], [9, 10]])

# multiply the matrices using numpy.dot()
C = np.dot(A, B)

# print the result
print(C)


[[ 25  28]
 [ 57  64]
 [ 89 100]]


In [7]:
import numpy as np

# size of the checkerboard
n = 8

# create a (n x n) checkerboard pattern using NumPy broadcasting
checkerboard = np.zeros((n, n), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

# print the checkerboard pattern
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
